var goldButterfly = {
  width : 176, height : 176, bpp : 3,
  transparent : 5,
  buffer : atob("AHHHHHHHHHHHHHHHHHHHHHHAHHHHAHAAAAAAAAAAAAAAAEAAAAAAAAAAAAH33333nnGGGHEGGGHHHHHnnH33HHnnAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+++++2200wggkwg0000222+3++0020HHHHHAAAAAAHHHAAAAAAAAAAAHHAHAAAAAAAAAAAAAAAAEHGAAAAAAAAAA3333nnnGGGGGGGGGGHHHHnnH3nHnHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+/AAAAAAAAAA/++++2222200wwww0002222+282800HHHHAAAAAAAHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnHAAAAAAABAH3333nnnnnGGGGGGHGHHHHnH3nmHnHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2wAAAAAAAAAG++++22+000wggkwg000000++w2+200AAAAAAAAAAHHHHAAAAAAAAAAAHAHAAAAAAAAAAAAAAAAAAEAACAAAAAAAH333nnnHHGGGGGGGGHGHHHHHHHHnnnGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+++++2200wwg0wggA00002/402222wAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAG33333nnHGGGGGmGGGGGGGHH33HHnnHmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/+++++2000wg0wwgAA0000//+022202AAAAAAAAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3333n3HHGGGHmGGGGHHHHHH33HHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////+++2200ww20wwgk00wAg2+8020000AAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3333333HHHHGHGHGGGHHHHGGGH3GGHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////++++2200w200wgwA0wAA2+80000000AAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//3nn3nnnHGHnGHGHGGHGGHH3HHGHHHGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+0++2+20g2200wwgAwgA0n+wgk0000wAAAAAAAAAAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHGAAHAAH3H3HHHHHHnHGGHGGHGGHwH3GGHHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwwAAAAAA//+2220w+2000wgAggg8g+44AE0000wAAAAAAAAAAAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAHGABAAAAH33HnnHHnHnmHGGGGGH3H3GGGHHGGHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/++202++202wwgwwk++24A4gk0gAgwAAAAAAAAAAAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAHH3HnHnnHHmGGGGGHn3HkHGGHHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+2++++280wg0038+80AE4g00gAggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHAAABAAAAAAAG33333nHnHGGHHHHHHEAAHGGHHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggAAAAAAAAAAA//+++222002224AAgAAAGwkwAwgggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHEAAAAAAAAAAH333nnnnnHHnnHAGHHHGAHGHEHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAA///+++++2222wAAk++wAGw0ggwgwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAH/333H3nHHnHnGAEHHnHEHGHGHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////++++2++4AAAAA0wgAGwwAkgg0wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///33H33nn3AGEEAEHGGAHGGGHGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////+++4AAAAAAAAAAAG0wggmw0wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHH3333HHAAAAGEEAGEAAHHGGGHGHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG0wgkg00wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEGEAAEAHHGGGGHHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG0wg0000gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGGAAAAAAAAAAAAAAAAAAAAAAGEGAHAAHHGGHGHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG2w02000wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGAAAAAAAAAAAAAAAAAAAAAAAGGGAAAHnGGHHnmGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+80202wwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEGAAAHnmHHnHmGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+82202+2AHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGAAHHnnHHHHnHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++2+++40AAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGAGAGHnn3HnnHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2+2+2+82AAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGAGHnnnn3nHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+++2+00AAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGAAGH3n3nn3nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+++++++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAEGH333n3HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH++++++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGEAHAH333333AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHGGAAAH33333AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHAAHAH3//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHwAEHAAHAAH/AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4gwAAAAAAAAA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHHHHgEGEAHAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAkw4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHGGGHHAGGHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEggwgw3AAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHGGHHHAAAHGGAGHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG20ww3/44AAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHH3HHH3/HAAAAHHEHGHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG2+02///44AAAAAAAgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHn33Hn33/HAAAAAHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+++2////44AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHnnnHH333/3AAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+++22+///44AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH33mHHn333nAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+++002+///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3nHHHHH333HAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/++Aw022+/+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3nGGGHHHn3HAAAAAAAHHAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG++AAg022+++4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHnmEGGGHH333AAAAAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++wgAgw02+/+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHGGGH3Hn33AAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm+wwgAAm+22//+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAHHGGGGHmGHHn333AAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00wkgA+gg02+++/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHGHGHGGGHnHHn33AAAGAAAHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE000gk8gAg8gg22+/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAHHHHGHHGHmGGGHH33wAGGAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw20000wwm0wA002/+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEAAAAAAAAAAAAAAAAAAAAAAAAGHnHHHHHHHGGGGHH33wAGGHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA44AAAAAAAAAAAAAAAAAAAAAAAAA0+2002000wggg02//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAHGBAAAAAAAAAAAAAAAAHHnHHGHHHGGGHHnnn3wAGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA84AAAAAAAAAAAAAAAAAA2+000020wgk+22+++4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHAAAAAAAAAAAAAAAAAG3nHHGHHHHHGHHHn33HAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA84AAAAAAAAAAAAAAAAAg++0000200wgk02+///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAEG3HnGGHnHGGGGHHn333wAGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg+2+www20wgAg02+//+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHGAHCAAGG33GHGGGHGGGGHHn333HAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAg2+gg0ww0wwEg022+/+4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHAAA/AAGGGGHnmHGHGGGGGHHH3HHAEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG8wAA4AAAAAA/+00w0wgAgk220+2wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHAAHAEGGH33nHHGHHGGGGHHHHHHAGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+00AA/AAAA//++0wwwwggg0w0wwk2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHAAHHGGH333HHGGGHGGHHnHGGGHAAGEGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAA//++20wggwww+++0wgg04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAEHHHAAGH//3HHHGGGHHH33nGGGHHHAAEEEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAgAAAAH//++0wwgA4n//++0wgk2+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHAAAAAAAHAAAAAAAHH/33HHGGGGH3HH3HGGGGH3AAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAA//++20wgggwAAg28wgAw28AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAH333nHHGGGGGGGHHGGGHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//++0wwgAEwggg00wgA02wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAH/33HHGGGGHHGGGGHHmGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE/++20wgAAAw0wgAA0wm+wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH33nHHGGGHHHGGHGGHHHn3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm/++0wggAm000gEwgAg0+/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAH33HHGGGHnHGHGHHGGGGHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2/+20wgAm+0wwA2wwwgAAggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAH3nHHGGHnHHHGHHHHHGGGHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2++00gAG++0wgk04A0wwggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHHHEAAAAAAAAAAAAAAAAH3HHGGGH3nHGHHHHHGHHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4gA4AAAAAAAAAA4AAAAA2+20wgg/++wk00004AAggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAHHAAAAAAAAHAAAAAHHHHGHH33GHHGGGHH3EGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAGAAAAA2+20ww//4k00000wG/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAHHAAAAAHAAAAAAGAAAAAHnHGGH33HHHHGGHH332AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAA220wg0/4220wgk2+++wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAHAAAAAAAAHHAHHHGHHGHGGGGGGHHHHAHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAA4AAAAAA4+/A20ww03280wggAAA24gA+///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHnAHHGGHnGGGGGGGGGGHHH333333HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAA3AAAAAA/4A20wk02000wggAAAg2++///////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/HAAAAAAAAAAAAAAAAAAAHHGHHHHHHGGGGGGHHn33333333/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+AAAAAAAAAA4AAAAA4AA20g222200wgggAk22++////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAHAAAAAGAAHGGHHnHHHGGGGHHHHHGGHHHH3333wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwg2++2000wgg0000wwAA02+////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGHHHHGGGGGAAAAAAAAAAAHAAAGH2AHGHH3nHHHHHHGHHHHGGGGHHH32Hn3AAAAAAAAAAAAAAAAAAAAAAAAAAAAA000wwggAAAAAAAAAAAAAAAAAAA004AAwE+++2022+wgw0w2wgggk22+ww//AAAAAAAAAAAAAAAAAAAAAAAAAAGHHHHHHHHGGGEGGHGGEAAAAAGEHGGHHnAHGHn3nHHHHnGGHHH3GGEGHHH3GHH3AAAAAAAAAAAAAAAAAAAAAAAA2+++202////+AAA////+wwgAAAAAAw+003AA42/+gw02+wgggm/+wwgAk2++4G++AAAAAAAAAAAAAAAAAAAAAAAH3nnHHHH33/H/GGH//3333HHGAEAAAG3GGHAAmH3GGGHHHGGHGH33GHGGHH333HHHAAAAAAAAAAAAAAAAAAAAAG/++++022+///4/gE/////++++20wAAAAG+2/AA4/+Agw24AAAgggAAggggk++2+w02AAAAAAAAAAAAAAAAAAAAHn33nnHHHH333H/3HH///33333HHHHGAAAHnnnHHHHmGGHHGGGHHHHHGGGGGGHHHmGHHAAAAAAAAAAAAAAAAAAAG+++/+g0002+/+//4E/////+++++2002+AAAm+///2+gAg+4AG++200wwggggg02wggg0AAAAAAAAAAAAAAAAAAHHHnn3GGGGHHn33n3HH////33333nnHHHHHAAGH//3HHGGH3GHHnnHHHHHGGGGHHHGGGGHAAAAAAAAAAAAAAAAAE8wk2+gAAk0220022ww//////++++22000w0+AAH///++40+g/++++2200wwggggm+8wwAAAAAAAAAAAAAAAAAAGHGGHnHGGGGGGHHGHGGH3///33333nnHHHGHGH3AH3333H33H33333nHHHHHGGGGGH33HGGHAAAAAAAAAAAAAAAAwwgA2wggAAgw22+800w///////++++220000wgA+m///+24/////++++2200wwgggg3++2+/AAAAAAAAAAAAAAAHGGGHHGHGGGGGnnnnHHG3////33333nnHHGGGGGGHH3333HH33//3333nHHHHGGGGGGH33Hn3AAAAAAAAAAAAAAA88ww00wggAAA+2++000w///////++++200022++8w0///+g8//////++++2000wwgggwAg02/AAAAAAAAAAAAAAHHHHHHHGGGGGHnHH3HnmH3////33333nnnHHnnnnnHHH333GH3///333nnHnHHHHGGGHGGGHHHAAAAAAAAAAAAAG3+402+00wggA+02+02+8w//////++++20002220gA/+82+2g8/////++8000200wwgw+0wggw2AAAAAAAAAAAAAHHnnGHHHGGGGHGGHnGHnHHH3/3333333GGHHHnnGGHnHHGHHGH3///HGGHHHHHHHHHH3HnHGGHHAAAAAAAAAAAAAH2/82+200wgg+gw2w0202ww/////+/4w++20020wkwAA++w0wwm/+ggAAAA2++0www//3+8wgAAAAAAAAAAAAAAAHH3nHnHHHGGH3GGnHGHGH3HHH33333GH333GnnHGHGGG3HHGGHH3GGGGGGGHH3HHH3HHn3nGGGGAAAAAAAAAAAAAA4wm+++200w/AA2kgw2028+wg+/+w2//++002000wwgA++00w228wwwwwwgw2/4+//4//820wgAAAAAAAAAAAAAAAHHHnnnHHGH3GGnGGHnGHnn3HHHGH//333HHnnHHGGGH3GHGG3HHHHHHHHGGHn3H33/H/3GGGGGAAAAAAAAAAAAAAA43222802+wgG0gA2g02+///wA/////+202+2020w2/+Agg0+0g++82+00002+2+/4//+0wgAkAAAAAAAAAAAAAAAHHnHHHHHHHGHGGGHGGHn333HH3H///mnmH3nHnGGH3GGGGHHHGH33nHnHHHHnHnH3333HGGGHAAAAAAAAAAAAAAAAm42822+0wg+0gEwAk02+wwg/4////2+2++2222+/+gggAk0w+gww280++22+4wm+/2+0wgg0AAAAAAAAAAAAAAAAHHHHHHnHGHHGGHGGGHnHHGH3G///nn3H33nnnH33GGGGHGGH/GHGHHGHnnHn3GHH32nHGGHHAAAAAAAAAAAAAAAAAAAAAAw+8+80w20Ag02+2g2/4//+m++2/++2++/+00gggGE//wm820802+++222+++w0wAg2AAAAAAAAAAAAAAAAAAAAAAAH33nGG3GGGGnmnGn3Gn3Gn3nn333n333nHHGHGHG33HH3HHHHHn3HHHHHH3nGGGGHAAAAAAAAAAAAAAAAAAAAAAAA++20g8gAg022+k22www3//0//++++/+200wwg+42/+4n/80822+22000222+8wg0AAAAAAAAAAAAAAAAAAAAAAAAn3HGHnGGGGHH3GnnGGHn33n3333333nnHGHGGnHG333GH3HHHHHHHGHHHHH3H3GHAAAAAAAAAAAAAAAAAAAAAAAAH++020wAg00/0k00w////8+//++++++220+wg+0g3/+wA382+22+000000222+/+AAAAAAAAAAAAAAAAAAAAAAAAH3nHHnGGGGH3nHGGG33//HH/33n3333nnH3GHHHGHH33AH3HnHHHHHGGGHHHHnn3AAAAAAAAAAAAAAAAAAAAAAAAA++0220gA0//0kg00////3///+2++2++22002203g//4AAH82+++00000k00w++/AAAAAAAAAAAAAAAAAAAAAAAAAH3HHnGGGH33GHGGHH//3HH/3nn3333nnHHHHHnHGH33AAH3HHHnHHGHHHHHHHnnAAAAAAAAAAAAAAAAAAAAAAAAAA/+++2022/+w0gggg4/4/3/+22+2+++222222+24G+w4AAG2+++800000000028AAAAAAAAAAAAAAAAAAAAAAAAAAH33nHHHn33GHGGGGH3H/H3HnnnH333nHnHHH3H3HHGAAAHH333nGGGHHHHGHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAG+002//+g000gg/4//02022w3/+++0+++0+2/AA4AAAAw++++8000000000AAAAAAAAAAAAAAAAAAAAAAAAAAAAAG3GHn33nGnGGGGHH3/mnGnnHH3333H3nnHnH3AAHGAAAHH333nHHHHGHGHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3+22//+g2000wg+/+2k00m8//+++0+++8202gAA4AAAAw3++++0000wggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3nn3nnGmGmmGG33HmGGG3//3333Hn333HnHAAAHAAAAHH333H3HHHGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++/+0k02220g24gwg02/4///++++//+0+0+AAAAAAAA43//+2+000wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHn3GHHn3nHGHHHGGHn3H33333n3333HHHHAAAAAAAAHH3//HHHHGHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++022+++2ggA+gk02/2///++//+//228w4AAAAAAAA/+///+004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABADAn3GHH3333GGA3GHmn3HX3333H3H33HHnHHAAAAAAAAH3HHnHHHEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+022++2wwAHww202+////++0//+/+228/4AAAAAAAAAA4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHnHHnnHHACHGGmGnH3//333H333H3nH33wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAA+ggw028//////++++++++++4AAAAAAAAAAAAAAAAAAAA")
}

g.width = g.getWidth();
g.height = g.getHeight();

//Bluetooth on
var btOnImg = {
  width : 15, height : 22, bpp : 3,
  transparent : 2,
  buffer : E.toArrayBuffer(atob("/////H//////A/////4A/////4BH////4JI////4JJH///4J5I///4BP5I///BJ/5A//BJPP5A/4JJ5P5H4J/PL/JHBJf/5JI4JJ/7JJIBP75/ZJAJZPJ/JIBJJ5/JJHBJP/JJA4JJ/JJI/4JPJJI//4BJJA////AAH//A=="))
}
var btOffImg = {
  width : 15, height : 22, bpp : 1,
  buffer : E.toArrayBuffer(atob("AAAAwAcAGgBEAQgEEBgQIDCAIQAiACgAUABgAMABgAKACQARAEGDAPgA"))
}

//Charging symbol
var chrgOn = {
  width : 8, height : 15, bpp : 2,
  transparent : 0,
  palette : new Uint16Array([65535,65504,63488,64928]),
  buffer : E.toArrayBuffer(atob("qterVKlcrVClcLVAlVfVVA1cDVANQA3ADQAPAAwA"))
}

function draw() {
  g.clear();
  drawBackground();
  drawDate();
  drawTime();
  drawBattery();
  drawBluetooth();
  drawBatteryStatus();
}
function drawDate() {
  days = ["Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"];
  months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  var d = new Date();
  var dateString = `${days[d.getDay()]} ${months[d.getMonth()]} ${d.getDate()}`;
  //g.setFontTreasurehuntDOYwE_20(1);
  var sm = g.stringMetrics(dateString);
  g.setFont("Vector:18");
  g.setColor(1,1,1).drawString(dateString, 18, 45+38);
}

function drawTime(){
  g.setColor(1,1,1); //.fillRect(boxH).fillRect(boxM).clearRect(innerH).clearRect(innerM);
  g.setFont("Vector:42");
  
  //Draw the hour and minute
  //g.setFontTreasurehuntDOYwE_40_N(1);
  var d = new Date();
  var h = `${d.getHours()}`;
  var m = `00${d.getMinutes()}`.slice(-2);
  var t = `${h}:${m}`;
  var yOffset = 1; xOffset=2;
  g.setColor(1,1,1).drawString (t, 18,38);
}

function drawBattery(){
  var pad = 6; top=pad; bh=10; bw=40; linew=1;
  var box = {x:g.width-pad-bw,y:top,x2:g.width-pad,y2:top+bh};
  var innerB = {x:box.x+linew, y:box.y+linew, x2:box.x2-linew, y2:box.y2-linew};
  var batteryFill={x:box.x+linew, y:box.y+linew, x2:(box.x-linew)+bw*E.getBattery()/100, y2:box.y2-linew};
  g.setColor(1,1,1).fillRect(box).clearRect(innerB).setColor(0,1,0).fillRect(batteryFill);
}

function drawBluetooth(){
  var img;
  if (NRF.getSecurityStatus().connected) {
    img=btOnImg;
  } else {
    img=btOffImg;
  }
  //g.reset().drawImage(img,3,3);
}
function drawBatteryStatus(){
  var left = g.width - (20+6+4);
  var img;
  if (Bangle.isCharging()) {
    console.log("Charger connected");
    img=chrgOn;
    g.reset().drawImage(img,left, 4);
  } else {
    console.log("Charger not connected");
  }
}

function drawBackground() {
  var metrics = g.imageMetrics(goldButterfly);
  g.drawImage(goldButterfly, (g.width-metrics.width)/2, 0);
}

function nextBackground() {
  bgIndex++;
  if (bgIndex > backgrounds.length - 1) bgIndex = 0;
  if (bgIndex < 0) bgIndex = backgrounds.length - 1;
}
function prevBackground() {
  bgIndex--;
  if (bgIndex > backgrounds.length - 1) bgIndex = 0;
  if (bgIndex < 0) bgIndex = backgrounds.length - 1;
}

Bangle.on("touch", function (button, xy) {
  if (button == 1) {
    prevBackground();
  } else {
    nextBackground();
  }
  draw();
});

draw();
Bangle.setLocked(false);
Bangle.setLCDPower(true);
Bangle.setUI("clock");

NRF.on('connect', draw);
NRF.on('disconnect', draw);
Bangle.on("charging", draw);

var redrawTimerId = setInterval(function(){
   draw();
}, 60000);
